#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
            }
        }
    }
}

namespace TestFileHang
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountThread1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountThread2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountThread3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountThread4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountThread5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountThread6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountException1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountException2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountException3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountException4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountException5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CountException6;
    };
}

